name: Haskell CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.10.1'
        cabal-version: '3.12.1'

    - name: Install C dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgc-dev build-essential hyperfine

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: |
        make
        make vm

    - name: Run tests
      run: make test_all -j

    - name: Run benchmarks
      run: tests/bench/benchmark.sh
